### ISSUE TITLE
plan to release new version?

### ISSUE THREAD

**Issue by neemit** [jasonkriss/ember-scroll-to#46] opened 2018-09-11 23:22 UTC
We need  ember-scroll-to v0.6.5 to fix some of our deprecated warnings related to ember-cli-babel 5.x 
Do you have any ETA to release v0.6.5?

**Comment by neemit** [comment] 2018-10-02 21:42
can someone please take a look at this?

**Comment by basz** [comment] 2018-10-05 09:26
@neemit please see #45

**Comment by blimmer** [comment] 2018-11-02 16:51
I sent an email today in accordance with the NPM policy disputes linked above. If the owner doesn't respond in 4 weeks, we should be able to take over ownership on the NPM side.

![screen shot 2018-11-02 at 10 49 57](https://user-images.githubusercontent.com/630449/47928923-33771f80-de8d-11e8-8e92-b30c9877d44f.png)

**Comment by blimmer** [comment] 2018-11-02 16:51
Closing as a dupe of the other issues opened #45 #40

**Closed as completed by blimmer** 2018-11-02 16:51 UTC
